//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace özel_projem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoodChatEntities7 : DbContext
    {
        public GoodChatEntities7()
            : base("name=GoodChatEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AdmLoginServices> AdmLoginServices { get; set; }
        public virtual DbSet<explore> explore { get; set; }
        public virtual DbSet<friends> friends { get; set; }
        public virtual DbSet<Hobby> Hobby { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Mess> Mess { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
